services:
  - type: web
    name: children-show-danmaku
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: BASE_URL
        sync: false

staticSites:
  - type: static
    name: quantum-computing
    routes:
      - source: /*
        destination: /index.html
    buildCommand: null
    publishDir: quantum-site
